DROP DATABASE IF EXISTS ESS;
CREATE DATABASE ESS;
USE ESS;
CREATE TABLE ADMIN(
ADMINNAME VARCHAR(20) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(20) NOT NULL
);
INSERT ADMIN VALUES('root','123456');
CREATE TABLE REQUEST(
FLOOR INT NOT NULL,
TYPE VARCHAR(4) NOT NULL,
TIME DATETIME NOT NULL
);
CREATE TABLE CONTROL(
ELEVATORID INT NOT NULL,
TIME DATETIME NOT NULL,
EVENT VARCHAR(15) NOT NULL
);
CREATE TABLE STATUS(
ELEVATORID INT PRIMARY KEY NOT NULL,
STATUS VARCHAR(10) NOT NULL,
CURRENTFLOOR INT NOT NULL
);
INSERT STATUS VALUES(0,'stop',1);